name: Frictionless Data
highlighter: rouge
markdown: kramdown
baseurl: 
exclude: ["ndjson/index.md"]
include: ["ndjson/README.md"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "spec"
  -
    scope:
      path: "ndjson"
    values:
      permalink: "/ndjson/index.html"
      listed: true
  -
    scope:
      path: "reference"
    values:
      reference: true
