blank_issues_enabled: false
contact_links:
  - name: ğŸ‘€ Explore Discussions
    url: https://github.com/frictionlessdata/datapackage/discussions
    about: Before opening a discussion, please check if the topic has already been discussed. Please vote on existing discussions to show your support.
  - name: ğŸ’¡ Feature Request
    url: https://github.com/frictionlessdata/datapackage/discussions/new?category=ideas
    about: Suggest an improvement youâ€™d like to see added to the Data Package Standard
  - name: ğŸš€ Implementation
    url: https://github.com/frictionlessdata/datapackage/discussions/new?category=show-and-tell
    about: Share your Data Package implementation or related project with the community
  - name: ğŸ’ Question
    url: https://github.com/frictionlessdata/datapackage/discussions/new?category=q-a
    about: Ask a question about the Data Package Standard
  - name: ğŸ‘¾ Chat
    url: https://join.slack.com/t/frictionlessdata/shared_invite/zt-17kpbffnm-tRfDW_wJgOw8tJVLvZTrBg
    about: Join the Data Package community on Slack!
